version: '3.8'

services:
  sync:
    build: .
    container_name: sync_woocommerce_odoo
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: ["python", "scripts/sync_orders.py"]
    restart: unless-stopped

  dashboard:
    build: .
    container_name: sync_dashboard
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: ["python", "scripts/admin_dashboard.py"]
    ports:
      - "8082:8081"
    restart: unless-stopped

volumes:
  odoo-data:
